import { College, Review, Discussion } from "@/types";

export const COLLEGES: College[] = [
  {
    id: "iit-bombay",
    name: "Indian Institute of Technology Bombay",
    location: "Mumbai, Maharashtra",
    city: "Mumbai",
    state: "Maharashtra",
    type: "Government",
    rating: 4.8,
    reviewCount: 3240,
    fees: { min: 220000, max: 250000 },
    ranking: 1,
    rankingBody: "NIRF 2024",
    image: "https://images.unsplash.com/photo-1562774053-701939374585?w=800",
    logo: "https://upload.wikimedia.org/wikipedia/en/thumb/b/b0/IIT_Bombay_Logo.svg/200px-IIT_Bombay_Logo.svg.png",
    established: 1958,
    accreditation: "NBA, NAAC",
    naacGrade: "A++",
    description: "IIT Bombay is one of India's premier engineering institutions, known for cutting-edge research and excellent industry connections. Located in Powai, Mumbai, it offers world-class education across engineering, sciences, and management.",
    website: "https://www.iitb.ac.in",
    phone: "+91-22-2572-2545",
    email: "info@iitb.ac.in",
    address: "Powai, Mumbai, Maharashtra 400076",
    admissionProcess: "JEE Advanced for B.Tech, GATE for M.Tech, JAM for M.Sc",
    tags: ["IIT", "Engineering", "Research", "Premium"],
    facilities: ["Library", "Hostel", "Sports Complex", "Medical Center", "Research Labs", "Cafeteria", "Gym", "Swimming Pool"],
    courses: [
      { id: "cse", name: "B.Tech Computer Science", duration: "4 years", fees: 250000, seats: 120, eligibility: "JEE Advanced", mode: "Full-time" },
      { id: "mech", name: "B.Tech Mechanical Engineering", duration: "4 years", fees: 250000, seats: 80, eligibility: "JEE Advanced", mode: "Full-time" },
      { id: "elec", name: "B.Tech Electrical Engineering", duration: "4 years", fees: 250000, seats: 90, eligibility: "JEE Advanced", mode: "Full-time" },
      { id: "mtech-cse", name: "M.Tech Computer Science", duration: "2 years", fees: 120000, seats: 60, eligibility: "GATE", mode: "Full-time" },
    ],
    placements: { averageSalary: 2200000, highestSalary: 25000000, placementRate: 97, topRecruiters: ["Google", "Microsoft", "Amazon", "Goldman Sachs", "DE Shaw"], year: 2024 },
    cutoffs: [
      { exam: "JEE Advanced", category: "General", openingRank: 1, closingRank: 63, year: 2024 },
      { exam: "JEE Advanced", category: "OBC-NCL", openingRank: 10, closingRank: 120, year: 2024 },
    ],
    gallery: ["https://images.unsplash.com/photo-1562774053-701939374585?w=400", "https://images.unsplash.com/photo-1541339907198-e08756dedf3f?w=400"],
  },
  {
    id: "iit-delhi",
    name: "Indian Institute of Technology Delhi",
    location: "New Delhi, Delhi",
    city: "New Delhi",
    state: "Delhi",
    type: "Government",
    rating: 4.7,
    reviewCount: 2980,
    fees: { min: 220000, max: 245000 },
    ranking: 2,
    rankingBody: "NIRF 2024",
    image: "https://images.unsplash.com/photo-1580582932707-520aed937b7b?w=800",
    logo: "https://upload.wikimedia.org/wikipedia/en/thumb/0/01/IIT_Delhi_Logo.svg/200px-IIT_Delhi_Logo.svg.png",
    established: 1961,
    accreditation: "NBA, NAAC",
    naacGrade: "A++",
    description: "IIT Delhi is a world-renowned institution known for its academic excellence and research output. Located in the heart of New Delhi, it provides unmatched industry exposure and placement opportunities.",
    website: "https://home.iitd.ac.in",
    phone: "+91-11-2659-1999",
    email: "info@iitd.ac.in",
    address: "Hauz Khas, New Delhi 110016",
    admissionProcess: "JEE Advanced for B.Tech, GATE for M.Tech",
    tags: ["IIT", "Engineering", "Research", "Premium"],
    facilities: ["Library", "Hostel", "Sports Complex", "Medical Center", "Innovation Hub"],
    courses: [
      { id: "cse", name: "B.Tech Computer Science", duration: "4 years", fees: 245000, seats: 90, eligibility: "JEE Advanced", mode: "Full-time" },
      { id: "civil", name: "B.Tech Civil Engineering", duration: "4 years", fees: 245000, seats: 80, eligibility: "JEE Advanced", mode: "Full-time" },
    ],
    placements: { averageSalary: 2100000, highestSalary: 22000000, placementRate: 96, topRecruiters: ["Google", "Microsoft", "Flipkart", "McKinsey", "BCG"], year: 2024 },
    cutoffs: [
      { exam: "JEE Advanced", category: "General", openingRank: 5, closingRank: 98, year: 2024 },
    ],
    gallery: ["https://images.unsplash.com/photo-1580582932707-520aed937b7b?w=400"],
  },
  {
    id: "bits-pilani",
    name: "BITS Pilani",
    location: "Pilani, Rajasthan",
    city: "Pilani",
    state: "Rajasthan",
    type: "Deemed",
    rating: 4.6,
    reviewCount: 4120,
    fees: { min: 500000, max: 600000 },
    ranking: 7,
    rankingBody: "NIRF 2024",
    image: "https://images.unsplash.com/photo-1523050854058-8df90110c9f1?w=800",
    logo: "",
    established: 1964,
    accreditation: "NAAC",
    naacGrade: "A",
    description: "BITS Pilani is a premier private engineering university known for its dual degree program and industry-integrated curriculum. It offers one of the best placement records among private institutions.",
    website: "https://www.bits-pilani.ac.in",
    phone: "+91-1596-242192",
    email: "admissions@pilani.bits-pilani.ac.in",
    address: "Vidya Vihar, Pilani, Rajasthan 333031",
    admissionProcess: "BITSAT entrance exam",
    tags: ["Private", "Engineering", "Top Private", "Dual Degree"],
    facilities: ["Library", "Hostel", "Sports", "Labs", "Auditorium"],
    courses: [
      { id: "cse", name: "B.E. Computer Science", duration: "4 years", fees: 595000, seats: 140, eligibility: "BITSAT", mode: "Full-time" },
      { id: "eco", name: "B.E. Electronics & Communication", duration: "4 years", fees: 595000, seats: 120, eligibility: "BITSAT", mode: "Full-time" },
    ],
    placements: { averageSalary: 1800000, highestSalary: 15000000, placementRate: 95, topRecruiters: ["Amazon", "Microsoft", "Uber", "Salesforce", "Oracle"], year: 2024 },
    cutoffs: [
      { exam: "BITSAT", category: "General", openingRank: 280, closingRank: 380, year: 2024 },
    ],
    gallery: ["https://images.unsplash.com/photo-1523050854058-8df90110c9f1?w=400"],
  },
  {
    id: "nit-trichy",
    name: "National Institute of Technology Tiruchirappalli",
    location: "Tiruchirappalli, Tamil Nadu",
    city: "Tiruchirappalli",
    state: "Tamil Nadu",
    type: "Government",
    rating: 4.5,
    reviewCount: 2650,
    fees: { min: 150000, max: 175000 },
    ranking: 8,
    rankingBody: "NIRF 2024",
    image: "https://images.unsplash.com/photo-1597733336794-12d05021d510?w=800",
    logo: "",
    established: 1964,
    accreditation: "NBA, NAAC",
    naacGrade: "A++",
    description: "NIT Trichy is the top-ranked NIT in India, known for its strong engineering programs and excellent campus placements.",
    website: "https://www.nitt.edu",
    phone: "+91-431-250-3000",
    email: "director@nitt.edu",
    address: "National Highway 45, Tiruchirappalli, Tamil Nadu 620015",
    admissionProcess: "JEE Main",
    tags: ["NIT", "Engineering", "Government"],
    facilities: ["Library", "Hostel", "Sports", "Research Labs"],
    courses: [
      { id: "cse", name: "B.Tech Computer Science", duration: "4 years", fees: 175000, seats: 60, eligibility: "JEE Main", mode: "Full-time" },
    ],
    placements: { averageSalary: 1400000, highestSalary: 12000000, placementRate: 94, topRecruiters: ["TCS", "Infosys", "Wipro", "Amazon", "Zoho"], year: 2024 },
    cutoffs: [
      { exam: "JEE Main", category: "General", openingRank: 1200, closingRank: 2800, year: 2024 },
    ],
    gallery: [],
  },
  {
    id: "vit-vellore",
    name: "Vellore Institute of Technology",
    location: "Vellore, Tamil Nadu",
    city: "Vellore",
    state: "Tamil Nadu",
    type: "Deemed",
    rating: 4.2,
    reviewCount: 8540,
    fees: { min: 395000, max: 450000 },
    ranking: 11,
    rankingBody: "NIRF 2024",
    image: "https://images.unsplash.com/photo-1607237138185-eedd9c632b0b?w=800",
    logo: "",
    established: 1984,
    accreditation: "NAAC",
    naacGrade: "A++",
    description: "VIT Vellore is one of India's largest private engineering universities, known for its international collaborations, diverse student community, and strong corporate connections.",
    website: "https://vit.ac.in",
    phone: "+91-416-220-2020",
    email: "admissions@vit.ac.in",
    address: "Vellore, Tamil Nadu 632014",
    admissionProcess: "VITEEE entrance exam",
    tags: ["Private", "Engineering", "International", "Large Campus"],
    facilities: ["Library", "Hostel", "Sports Complex", "Food Court", "Medical", "International Relations Cell"],
    courses: [
      { id: "cse", name: "B.Tech Computer Science", duration: "4 years", fees: 450000, seats: 600, eligibility: "VITEEE", mode: "Full-time" },
      { id: "cse-ai", name: "B.Tech CSE with AI/ML", duration: "4 years", fees: 450000, seats: 300, eligibility: "VITEEE", mode: "Full-time" },
    ],
    placements: { averageSalary: 800000, highestSalary: 8000000, placementRate: 90, topRecruiters: ["TCS", "Wipro", "Cognizant", "Capgemini", "L&T"], year: 2024 },
    cutoffs: [],
    gallery: [],
  },
  {
    id: "srm-chennai",
    name: "SRM Institute of Science and Technology",
    location: "Kattankulathur, Tamil Nadu",
    city: "Chennai",
    state: "Tamil Nadu",
    type: "Deemed",
    rating: 4.0,
    reviewCount: 5230,
    fees: { min: 280000, max: 400000 },
    ranking: 22,
    rankingBody: "NIRF 2024",
    image: "https://images.unsplash.com/photo-1517842645767-c639042777db?w=800",
    logo: "",
    established: 1985,
    accreditation: "NAAC",
    naacGrade: "A++",
    description: "SRM is a prominent private university known for its engineering programs, modern infrastructure, and growing research output.",
    website: "https://www.srmist.edu.in",
    phone: "+91-44-2745-6218",
    email: "admissions@srmist.edu.in",
    address: "SRM Nagar, Kattankulathur, Tamil Nadu 603203",
    admissionProcess: "SRMJEEE entrance exam or 12th marks",
    tags: ["Private", "Engineering", "Large University"],
    facilities: ["Hostel", "Library", "Sports", "Medical"],
    courses: [
      { id: "cse", name: "B.Tech Computer Science", duration: "4 years", fees: 400000, seats: 800, eligibility: "SRMJEEE", mode: "Full-time" },
    ],
    placements: { averageSalary: 600000, highestSalary: 5000000, placementRate: 85, topRecruiters: ["TCS", "Infosys", "Wipro", "HCL", "Accenture"], year: 2024 },
    cutoffs: [],
    gallery: [],
  },
  {
    id: "du-north-campus",
    name: "University of Delhi (North Campus)",
    location: "New Delhi, Delhi",
    city: "New Delhi",
    state: "Delhi",
    type: "Government",
    rating: 4.4,
    reviewCount: 6780,
    fees: { min: 30000, max: 80000 },
    ranking: 13,
    rankingBody: "NIRF 2024",
    image: "https://images.unsplash.com/photo-1592280771190-3e2e4d571952?w=800",
    logo: "",
    established: 1922,
    accreditation: "NAAC",
    naacGrade: "A++",
    description: "Delhi University is India's premier central university offering diverse programs in arts, science, commerce, and professional courses across its prestigious colleges.",
    website: "https://www.du.ac.in",
    phone: "+91-11-2766-7725",
    email: "registrar@du.ac.in",
    address: "University Enclave, North Campus, New Delhi 110007",
    admissionProcess: "CUET (Common University Entrance Test)",
    tags: ["Central University", "Arts", "Science", "Commerce"],
    facilities: ["Library", "Hostel", "Sports", "Cultural Centers"],
    courses: [
      { id: "bsc-cs", name: "B.Sc. Computer Science", duration: "3 years", fees: 50000, seats: 200, eligibility: "CUET", mode: "Full-time" },
      { id: "bcom", name: "B.Com (Hons)", duration: "3 years", fees: 30000, seats: 400, eligibility: "CUET", mode: "Full-time" },
      { id: "ba-eco", name: "B.A. Economics (Hons)", duration: "3 years", fees: 30000, seats: 300, eligibility: "CUET", mode: "Full-time" },
    ],
    placements: { averageSalary: 600000, highestSalary: 4000000, placementRate: 75, topRecruiters: ["Deloitte", "PwC", "EY", "KPMG", "Unilever"], year: 2024 },
    cutoffs: [],
    gallery: [],
  },
  {
    id: "iim-ahmedabad",
    name: "Indian Institute of Management Ahmedabad",
    location: "Ahmedabad, Gujarat",
    city: "Ahmedabad",
    state: "Gujarat",
    type: "Government",
    rating: 4.9,
    reviewCount: 1890,
    fees: { min: 2500000, max: 2500000 },
    ranking: 1,
    rankingBody: "NIRF MBA 2024",
    image: "https://images.unsplash.com/photo-1541178735493-479c1a27ed24?w=800",
    logo: "",
    established: 1961,
    accreditation: "AACSB, EQUIS",
    naacGrade: "A++",
    description: "IIM Ahmedabad is Asia's premier management institution and one of the world's top business schools. It's known for its rigorous case-based learning and extraordinary alumni network.",
    website: "https://www.iima.ac.in",
    phone: "+91-79-6632-4709",
    email: "pgpadmissions@iima.ac.in",
    address: "Vastrapur, Ahmedabad, Gujarat 380015",
    admissionProcess: "CAT score + WAT + PI",
    tags: ["IIM", "MBA", "Management", "Premium"],
    facilities: ["Library", "Hostel", "Sports", "Incubation Center", "Amphitheater"],
    courses: [
      { id: "pgp", name: "PGP (MBA equivalent)", duration: "2 years", fees: 2500000, seats: 400, eligibility: "CAT 99+ percentile", mode: "Full-time" },
    ],
    placements: { averageSalary: 3500000, highestSalary: 100000000, placementRate: 100, topRecruiters: ["McKinsey", "BCG", "Bain", "Goldman Sachs", "JP Morgan"], year: 2024 },
    cutoffs: [],
    gallery: [],
  },
  {
    id: "iit-madras",
    name: "Indian Institute of Technology Madras",
    location: "Chennai, Tamil Nadu",
    city: "Chennai",
    state: "Tamil Nadu",
    type: "Government",
    rating: 4.8,
    reviewCount: 2780,
    fees: { min: 215000, max: 240000 },
    ranking: 1,
    rankingBody: "NIRF Overall 2024",
    image: "https://images.unsplash.com/photo-1509062522246-3755977927d7?w=800",
    logo: "",
    established: 1959,
    accreditation: "NBA, NAAC",
    naacGrade: "A++",
    description: "IIT Madras is ranked #1 overall in NIRF for consecutive years. It is known for its research excellence, startup ecosystem, and alumni network.",
    website: "https://www.iitm.ac.in",
    phone: "+91-44-2257-8280",
    email: "ugadmin@iitm.ac.in",
    address: "IIT P.O., Chennai, Tamil Nadu 600036",
    admissionProcess: "JEE Advanced for B.Tech, GATE for M.Tech",
    tags: ["IIT", "Engineering", "Research", "NIRF #1"],
    facilities: ["Library", "Hostel", "Research Park", "Sports", "Medical"],
    courses: [
      { id: "cse", name: "B.Tech Computer Science", duration: "4 years", fees: 240000, seats: 100, eligibility: "JEE Advanced", mode: "Full-time" },
    ],
    placements: { averageSalary: 2000000, highestSalary: 28000000, placementRate: 97, topRecruiters: ["Google", "Microsoft", "Apple", "Qualcomm", "Texas Instruments"], year: 2024 },
    cutoffs: [
      { exam: "JEE Advanced", category: "General", openingRank: 2, closingRank: 85, year: 2024 },
    ],
    gallery: [],
  },
  {
    id: "manipal-university",
    name: "Manipal Academy of Higher Education",
    location: "Manipal, Karnataka",
    city: "Manipal",
    state: "Karnataka",
    type: "Deemed",
    rating: 4.1,
    reviewCount: 7200,
    fees: { min: 320000, max: 600000 },
    ranking: 15,
    rankingBody: "NIRF 2024",
    image: "https://images.unsplash.com/photo-1562774053-701939374585?w=800",
    logo: "",
    established: 1953,
    accreditation: "NAAC",
    naacGrade: "A+",
    description: "Manipal University is a well-known private university offering diverse courses in engineering, medical, pharmacy, and management with strong international collaborations.",
    website: "https://manipal.edu",
    phone: "+91-820-292-1000",
    email: "admissions@manipal.edu",
    address: "Madhav Nagar, Manipal, Karnataka 576104",
    admissionProcess: "MET (Manipal Entrance Test) or Board merit",
    tags: ["Private", "Engineering", "Medical", "Management"],
    facilities: ["Hostel", "Library", "Hospital", "Sports", "Beach nearby"],
    courses: [
      { id: "cse", name: "B.Tech Computer Science", duration: "4 years", fees: 600000, seats: 300, eligibility: "MET", mode: "Full-time" },
      { id: "mbbs", name: "MBBS", duration: "5.5 years", fees: 800000, seats: 250, eligibility: "NEET", mode: "Full-time" },
    ],
    placements: { averageSalary: 750000, highestSalary: 6000000, placementRate: 88, topRecruiters: ["Infosys", "Wipro", "TCS", "Apollo", "Fortis"], year: 2024 },
    cutoffs: [],
    gallery: [],
  },
  {
    id: "anna-university",
    name: "Anna University",
    location: "Chennai, Tamil Nadu",
    city: "Chennai",
    state: "Tamil Nadu",
    type: "Government",
    rating: 4.3,
    reviewCount: 4560,
    fees: { min: 60000, max: 120000 },
    ranking: 5,
    rankingBody: "NIRF Engineering 2024",
    image: "https://images.unsplash.com/photo-1581362781993-e57e49f4e3e8?w=800",
    logo: "",
    established: 1978,
    accreditation: "NAAC",
    naacGrade: "A++",
    description: "Anna University is Tamil Nadu's premier technical university, offering world-class engineering education to thousands of students through its affiliated colleges network.",
    website: "https://www.annauniv.edu",
    phone: "+91-44-2235-7000",
    email: "coe@annauniv.edu",
    address: "Sardar Patel Road, Guindy, Chennai, Tamil Nadu 600025",
    admissionProcess: "TNEA (Tamil Nadu Engineering Admissions) based on 12th marks",
    tags: ["Government", "Engineering", "Tamil Nadu"],
    facilities: ["Library", "Hostel", "Labs", "Sports"],
    courses: [
      { id: "cse", name: "B.E. Computer Science", duration: "4 years", fees: 120000, seats: 120, eligibility: "TNEA", mode: "Full-time" },
    ],
    placements: { averageSalary: 500000, highestSalary: 4000000, placementRate: 82, topRecruiters: ["TCS", "Infosys", "Wipro", "HCL", "CTS"], year: 2024 },
    cutoffs: [],
    gallery: [],
  },
  {
    id: "presidency-college",
    name: "Presidency College, Chennai",
    location: "Chennai, Tamil Nadu",
    city: "Chennai",
    state: "Tamil Nadu",
    type: "Government",
    rating: 4.3,
    reviewCount: 2100,
    fees: { min: 10000, max: 25000 },
    ranking: 3,
    rankingBody: "NIRF Arts & Science 2024",
    image: "https://images.unsplash.com/photo-1503676260728-1c00da094a0b?w=800",
    logo: "",
    established: 1840,
    accreditation: "NAAC",
    naacGrade: "A+",
    description: "One of India's oldest and most prestigious liberal arts colleges, Presidency College has a rich heritage of academic excellence in sciences, arts and humanities.",
    website: "https://www.presidency.unom.ac.in",
    phone: "+91-44-2854-3022",
    email: "presicollege@nic.in",
    address: "35, Kamarajar Salai, Chennai, Tamil Nadu 600005",
    admissionProcess: "Tamil Nadu State Merit + Special Category",
    tags: ["Arts & Science", "Heritage", "Government"],
    facilities: ["Library", "Museum", "Labs", "Sports"],
    courses: [
      { id: "bsc-maths", name: "B.Sc. Mathematics", duration: "3 years", fees: 15000, seats: 80, eligibility: "State Merit", mode: "Full-time" },
      { id: "bsc-physics", name: "B.Sc. Physics", duration: "3 years", fees: 15000, seats: 60, eligibility: "State Merit", mode: "Full-time" },
    ],
    placements: { averageSalary: 400000, highestSalary: 2000000, placementRate: 65, topRecruiters: ["State Bank", "Railways", "ISRO", "DRDO"], year: 2024 },
    cutoffs: [],
    gallery: [],
  },
];

export const REVIEWS: Review[] = [
  {
    id: "r1", collegeId: "iit-bombay", userId: "u1",
    userName: "Rahul Sharma", avatar: "https://i.pravatar.cc/60?img=11",
    rating: 5, title: "Best decision of my life",
    pros: "World-class faculty, excellent peer group, amazing placement support, research opportunities are unmatched. The campus life is vibrant and the alumni network is incredible.",
    cons: "Academics are very intense. Work-life balance can be challenging especially in first year.",
    batch: "2020-24", course: "B.Tech CSE", helpful: 234, createdAt: "2024-06-15",
  },
  {
    id: "r2", collegeId: "iit-bombay", userId: "u2",
    userName: "Priya Nair", avatar: "https://i.pravatar.cc/60?img=25",
    rating: 4, title: "Great for research and placements",
    pros: "Excellent professors, great infrastructure, fantastic research opportunities. Internships from top companies in 3rd year.",
    cons: "Hostel rooms are a bit small. Food in mess can be inconsistent. Expensive fees for international students.",
    batch: "2021-25", course: "B.Tech Electrical", helpful: 178, createdAt: "2024-05-20",
  },
];

export const DISCUSSIONS: Discussion[] = [
  {
    id: "d1", title: "IIT Bombay vs IIT Delhi for CSE — which one should I choose?",
    body: "I have secured a rank that allows me to get CSE in both IIT Bombay and IIT Delhi. Considering placements, research, and campus life, which one would be better? Any insights from current students or alumni would be highly appreciated.",
    tags: ["IIT Bombay", "IIT Delhi", "CSE", "Admissions"],
    author: { id: "u3", name: "Ankit Mehta", avatar: "https://i.pravatar.cc/60?img=33" },
    answers: [
      {
        id: "a1", body: "Both are excellent choices! IIT Bombay has a slight edge in placements due to Mumbai's proximity to MNCs and startups. IIT Delhi scores better if you want government/PSU connections given its location in the capital. For research, both are comparable.",
        author: { id: "u4", name: "Vikram Singh", avatar: "https://i.pravatar.cc/60?img=52" },
        votes: 89, isAccepted: true, createdAt: "2024-07-10",
      },
    ],
    views: 4530, votes: 156, createdAt: "2024-07-08", collegeId: "iit-bombay",
  },
  {
    id: "d2", title: "BITS Pilani vs NIT Trichy for ECE — fees vs reputation?",
    body: "BITS Pilani ECE fee is around 6L per year vs NIT Trichy ECE which is around 1.5L per year. Is BITS worth the extra cost considering placements and brand value?",
    tags: ["BITS Pilani", "NIT Trichy", "ECE", "Fees"],
    author: { id: "u5", name: "Deepika Rao", avatar: "https://i.pravatar.cc/60?img=47" },
    answers: [],
    views: 2780, votes: 92, createdAt: "2024-07-12",
  },
];